networks:
  borrow-networks:
    driver: bridge

services:
  pgdb:
    image: postgres:16-alpine
    container_name: pgdb
    restart: unless-stopped
    ports:
      - "5630:5432"
    environment:
      POSTGRES_DB: TestDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TestDb"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - borrow-networks

  install:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turbo-install
    working_dir: /repo
    environment:
      CI: "true"
      PNPM_HOME: "/pnpm-store"
    volumes:
      - .:/repo
      - pnpm_store:/pnpm-store
      - root_node_modules:/repo/node_modules
      - api_node_modules:/repo/apps/api/node_modules
      - web_node_modules:/repo/apps/web/node_modules
    # ใช้ --unsafe-perm ถ้าเจอปัญหาเรื่องสิทธิ์ตอนติดตั้งบน Linux
    command: pnpm install --no-frozen-lockfile
    restart: "no"
    networks:
      - borrow-networks

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turbo-api
    working_dir: /repo
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - .:/repo
      - pnpm_store:/pnpm-store #cahce ของ pnpm ทำให้ build เร็วขึ้น
      - root_node_modules:/repo/node_modules #node_module กลาง
      - api_node_modules:/repo/apps/api/node_modules #เอาไว้เก็บ deps ของ api
    depends_on:
      pgdb:
        condition: service_healthy
      install:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql://postgres:123456@pgdb:5432/TestDb"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${CALLBACK_URL}
      JWT_SECRET: ${JWT_SECRET}
      CHOKIDAR_USEPOLLING: "true"
      CI: "true"
      PNPM_HOME: "/pnpm-store"
    # รัน prisma generate ใน container เสมอ
    command: >
      sh -c "
        cd apps/api &&
        pnpm exec prisma generate &&
        pnpm run dev
      "

    networks:
      - borrow-networks

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turbo-web
    working_dir: /repo
    ports:
      - "3000:3000"
    volumes:
      - .:/repo
      - pnpm_store:/pnpm-store
      - root_node_modules:/repo/node_modules
      - web_node_modules:/repo/apps/web/node_modules
    depends_on:
      install:
        condition: service_completed_successfully
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CI: "true"
      PNPM_HOME: "/pnpm-store"
    command: pnpm turbo dev --filter=web...
    networks:
      - borrow-networks

volumes:
  pg_data:
  pnpm_store:
  root_node_modules:
  api_node_modules:
  web_node_modules:
