FROM node:20-alpine

WORKDIR /repo

RUN corepack enable && corepack prepare pnpm@10.19.0 --activate
RUN pnpm config set store-dir /pnpm-store --global

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps ./apps