import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { lineSeed } from "@/fonts/font";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lineSeed.className}>{children}</body>
    </html>
  );
}
