import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { lineSeed } from "@/fonts/font";
import Providers from "@/provider/query-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "บริการยืมคืน",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={lineSeed.className}>
          <Toaster />
          {children}
        </body>
      </Providers>
    </html>
  );
}
